version: "3"

services:
  app:
    build: .
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ffxdb
      - POSTGRES_USER=steve
      - POSTGRES_PASSWORD=vbflrtms18@
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - ./docker/data:/var/lib/postgresql/data
